namespace Orchestify.Shared.Constants;

/// <summary>
/// Defines standard HTTP header names used throughout the Orchestify platform.
/// Centralizes header constants to prevent magic strings and ensure consistency.
/// </summary>
public static class HttpHeaderConstants
{
    /// <summary>
    /// Header for tracking requests across service boundaries.
    /// Clients may provide this header; if omitted, the server generates a new GUID.
    /// Included in all API responses and logged for distributed tracing.
    /// </summary>
    public const string CorrelationId = "X-Correlation-Id";

    /// <summary>
    /// Header for unique request identification.
    /// Generated by the server for each incoming request.
    /// Useful for differentiating multiple requests with the same correlation ID.
    /// </summary>
    public const string RequestId = "X-Request-Id";

    /// <summary>
    /// Header specifying the unique idempotency key for idempotent operations.
    /// Prevents duplicate processing of the same request.
    /// Required for POST/PATCH/DELETE operations that modify state.
    /// </summary>
    public const string IdempotencyKey = "X-Idempotency-Key";

    /// <summary>
    /// Header used for API version negotiation.
    /// Allows clients to request a specific API version.
    /// Format: v1, v2, etc.
    /// </summary>
    public const string ApiVersion = "X-API-Version";

    /// <summary>
    /// Header for authentication token.
    /// Contains the JWT bearer token for authorization.
    /// Format: Bearer {token}
    /// </summary>
    public const string Authorization = "Authorization";

    /// <summary>
    /// Header for specifying the content type of the request body.
    /// Defaults to application/json for REST APIs.
    /// </summary>
    public const string ContentType = "Content-Type";

    /// <summary>
    /// Header for specifying acceptable response content types.
    /// Used for content negotiation.
    /// </summary>
    public const string Accept = "Accept";

    /// <summary>
    /// Header identifying the original client application making the request.
    /// Useful for analytics and client-specific behavior.
    /// </summary>
    public const string UserAgent = "User-Agent";

    /// <summary>
    /// Header for specifying the tenant identifier in multi-tenant scenarios.
    /// Required for all requests in multi-tenant deployments.
    /// </summary>
    public const string TenantId = "X-Tenant-Id";
}
